### ISSUE TITLE
Face ID not working

### ISSUE THREAD

**Issue by thiyagu83j** [NiklasMerz/cordova-plugin-fingerprint-aio#363]
FingerPrint is working but FaceID is not working. Iam using samsung j7 mobile. I enabled both fingerprint and face . If i disabled fingerprint. The result is given error as "At least one biometric must be enrolled to create keys" error code: -100. Can anybody please provide solution.

**Comment by sonnylloyd** [comment]
FaceID does not work on IOS 14.7.1. 

I wish i could be more help on this. But i dont own an iphone device. I only know this does not work because of a friend.

**Comment by NiklasMerz** [comment]
This plugin uses a standard Android API for biometric authentication. Possibly the face id of your device does not implement this API. Unfortunately the many Android devices have many specialties this plugin cannot support.
