### ISSUE TITLE
Build iOS error: value of type 'LAContext' has no member 'biometryType'

### ISSUE THREAD

**Issue by carned** [NiklasMerz/cordova-plugin-fingerprint-aio#110]
Hello,
I have a problem building on iOS platform
`ionic cordova emulate ios`
Result:
```
cordova-plugin-fingerprint-aio/Fingerprint.swift:18:24: error: value of type 'LAContext' has no member 'biometryType'
                switch(authenticationContext.biometryType) {
                       ^~~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~

** BUILD FAILED **
```

I put into config.xml this preferences:
`<preference name="UseSwiftLanguageVersion" value="3.2" />`

## Environment

```
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

global packages:

    cordova (Cordova CLI) : 8.0.0

local packages:

    @ionic/app-scripts : 3.1.11
    Cordova Platforms  : ios 4.5.5
    Ionic Framework    : ionic-angular 3.9.2

System:

    ios-deploy : 1.8.6
    ios-sim    : 5.0.8
    Node       : v6.9.4
    npm        : 4.1.1
    OS         : macOS Sierra
    Xcode      : Xcode 8.0 Build version 8A218a
```

Thanks

**Comment by NiklasMerz** [comment]
Sorry, this plugin only build with Xcode 9.2 and above.
